import FWCore.ParameterSet.Config as cms

pftauMaker = cms.EDProducer("PFTauMaker",
	aliasPrefix = cms.untracked.string("taus_pf"),
        cms2PFJetsTag = cms.InputTag("prunedUncorrectedCMS2Jets", "pfjet"),
        referencePFJetsTag = cms.InputTag("ak5PFJets"),
        particleFlowTag = cms.InputTag("particleFlow"),
        # PFTau collection
        pftausInputTag = cms.InputTag("hpsPFTauProducer"),
        # discriminator
	byLooseElectronRejection=cms.InputTag("hpsPFTauDiscriminationByLooseElectronRejection"),
	byMediumElectronRejection=cms.InputTag("hpsPFTauDiscriminationByMediumElectronRejection"),
	byTightElectronRejection=cms.InputTag("hpsPFTauDiscriminationByTightElectronRejection"),
	byMVA5LooseElectronRejection=cms.InputTag("hpsPFTauDiscriminationByMVA5LooseElectronRejection"),
	byMVA5MediumElectronRejection=cms.InputTag("hpsPFTauDiscriminationByMVA5MediumElectronRejection"),
	byMVA5TightElectronRejection=cms.InputTag("hpsPFTauDiscriminationByMVA5TightElectronRejection"),
	byMVA5VTightElectronRejection=cms.InputTag("hpsPFTauDiscriminationByMVA5VTightElectronRejection"),
	byLooseMuonRejection=cms.InputTag("hpsPFTauDiscriminationByLooseMuonRejection"),
	byMediumMuonRejection=cms.InputTag("hpsPFTauDiscriminationByMediumMuonRejection"),
	byTightMuonRejection=cms.InputTag("hpsPFTauDiscriminationByTightMuonRejection"),
	byLooseMuonRejection3=cms.InputTag("hpsPFTauDiscriminationByLooseMuonRejection3"),
	byTightMuonRejection3=cms.InputTag("hpsPFTauDiscriminationByTightMuonRejection3"),
	byMVALooseMuonRejection=cms.InputTag("hpsPFTauDiscriminationByMVALooseMuonRejection"),
	byMVAMediumMuonRejection=cms.InputTag("hpsPFTauDiscriminationByMVAMediumMuonRejection"),
	byMVATightMuonRejection=cms.InputTag("hpsPFTauDiscriminationByMVATightMuonRejection"),
	byMVArawMuonRejection=cms.InputTag("hpsPFTauDiscriminationByMVArawMuonRejection"),
	byDecayModeFinding=cms.InputTag("hpsPFTauDiscriminationByDecayModeFinding"),
	byVLooseIsolation=cms.InputTag("hpsPFTauDiscriminationByVLooseIsolation"),
	byVLooseCombinedIsolationDBSumPtCorr=cms.InputTag("hpsPFTauDiscriminationByVLooseCombinedIsolationDBSumPtCorr"),
	byLooseCombinedIsolationDBSumPtCorr=cms.InputTag("hpsPFTauDiscriminationByLooseCombinedIsolationDBSumPtCorr"),
	byMediumCombinedIsolationDBSumPtCorr=cms.InputTag("hpsPFTauDiscriminationByMediumCombinedIsolationDBSumPtCorr"),
	byTightCombinedIsolationDBSumPtCorr=cms.InputTag("hpsPFTauDiscriminationByTightCombinedIsolationDBSumPtCorr"),
	byLooseCombinedIsolationDBSumPtCorr3Hits=cms.InputTag("hpsPFTauDiscriminationByLooseCombinedIsolationDBSumPtCorr3Hits"),
	byMediumCombinedIsolationDBSumPtCorr3Hits=cms.InputTag("hpsPFTauDiscriminationByMediumCombinedIsolationDBSumPtCorr3Hits"),
	byTightCombinedIsolationDBSumPtCorr3Hits=cms.InputTag("hpsPFTauDiscriminationByTightCombinedIsolationDBSumPtCorr3Hits"),
	byVLooseIsolationMVA3oldDMwoLT=cms.InputTag("hpsPFTauDiscriminationByVLooseIsolationMVA3oldDMwoLT"),
	byLooseIsolationMVA3oldDMwoLT=cms.InputTag("hpsPFTauDiscriminationByLooseIsolationMVA3oldDMwoLT"),
	byMediumIsolationMVA3oldDMwoLT=cms.InputTag("hpsPFTauDiscriminationByMediumIsolationMVA3oldDMwoLT"),
	byTightIsolationMVA3oldDMwoLT=cms.InputTag("hpsPFTauDiscriminationByTightIsolationMVA3oldDMwoLT"),
	byVTightIsolationMVA3oldDMwoLT=cms.InputTag("hpsPFTauDiscriminationByVTightIsolationMVA3oldDMwoLT"),
	byVVTightIsolationMVA3oldDMwoLT=cms.InputTag("hpsPFTauDiscriminationByVVTightIsolationMVA3oldDMwoLT"),
	byIsolationMVA3oldDMwoLTraw=cms.InputTag("hpsPFTauDiscriminationByIsolationMVA3oldDMwoLTraw"),
	byVLooseIsolationMVA3oldDMwLT=cms.InputTag("hpsPFTauDiscriminationByVLooseIsolationMVA3oldDMwLT"),
	byLooseIsolationMVA3oldDMwLT=cms.InputTag("hpsPFTauDiscriminationByLooseIsolationMVA3oldDMwLT"),
	byMediumIsolationMVA3oldDMwLT=cms.InputTag("hpsPFTauDiscriminationByMediumIsolationMVA3oldDMwLT"),
	byTightIsolationMVA3oldDMwLT=cms.InputTag("hpsPFTauDiscriminationByTightIsolationMVA3oldDMwLT"),
	byVTightIsolationMVA3oldDMwLT=cms.InputTag("hpsPFTauDiscriminationByVTightIsolationMVA3oldDMwLT"),
	byVVTightIsolationMVA3oldDMwLT=cms.InputTag("hpsPFTauDiscriminationByVVTightIsolationMVA3oldDMwLT"),
	byIsolationMVA3oldDMwLTraw=cms.InputTag("hpsPFTauDiscriminationByIsolationMVA3oldDMwLTraw"),
	byVLooseIsolationMVA3newDMwoLT=cms.InputTag("hpsPFTauDiscriminationByVLooseIsolationMVA3newDMwoLT"),
	byLooseIsolationMVA3newDMwoLT=cms.InputTag("hpsPFTauDiscriminationByLooseIsolationMVA3newDMwoLT"),
	byMediumIsolationMVA3newDMwoLT=cms.InputTag("hpsPFTauDiscriminationByMediumIsolationMVA3newDMwoLT"),
	byTightIsolationMVA3newDMwoLT=cms.InputTag("hpsPFTauDiscriminationByTightIsolationMVA3newDMwoLT"),
	byVTightIsolationMVA3newDMwoLT=cms.InputTag("hpsPFTauDiscriminationByVTightIsolationMVA3newDMwoLT"),
	byVVTightIsolationMVA3newDMwoLT=cms.InputTag("hpsPFTauDiscriminationByVVTightIsolationMVA3newDMwoLT"),
	byIsolationMVA3newDMwoLTraw=cms.InputTag("hpsPFTauDiscriminationByIsolationMVA3newDMwoLTraw"),
	byVLooseIsolationMVA3newDMwLT=cms.InputTag("hpsPFTauDiscriminationByVLooseIsolationMVA3newDMwLT"),
	byLooseIsolationMVA3newDMwLT=cms.InputTag("hpsPFTauDiscriminationByLooseIsolationMVA3newDMwLT"),
	byMediumIsolationMVA3newDMwLT=cms.InputTag("hpsPFTauDiscriminationByMediumIsolationMVA3newDMwLT"),
	byTightIsolationMVA3newDMwLT=cms.InputTag("hpsPFTauDiscriminationByTightIsolationMVA3newDMwLT"),
	byVTightIsolationMVA3newDMwLT=cms.InputTag("hpsPFTauDiscriminationByVTightIsolationMVA3newDMwLT"),
	byVVTightIsolationMVA3newDMwLT=cms.InputTag("hpsPFTauDiscriminationByVVTightIsolationMVA3newDMwLT"),
	byIsolationMVA3newDMwLTraw=cms.InputTag("hpsPFTauDiscriminationByIsolationMVA3newDMwLTraw")

)




