import FWCore.ParameterSet.Config as cms

slimcms2 = cms.untracked.vstring()

#TrackMaker
slimcms2.extend(cms.untracked.vstring('drop *_trackMaker_trksvertexp4_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_trackMaker_trksouterp4_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_trackMaker_trksinnerposition_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_trackMaker_trksouterposition_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_trackMaker_trkslayer1layer_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_trackMaker_trkslayer1sizerphi_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_trackMaker_trkslayer1sizerz_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_trackMaker_trkslayer1charge_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_trackMaker_trkslayer1det_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_trackMaker_trksd0corrPhi_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_trackMaker_trksnlayers3D_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_trackMaker_trksnlayersLost_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_trackMaker_trkslostpixelhits_CMS2*'))

#Jet Collections
slimcms2.extend(cms.untracked.vstring('drop *_jptMaker_*_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_bTagJPTJetMaker_*_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_jetMaker_*_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_bTagMaker_*_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_trkJetMaker_*_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_bTagTrkMaker_*_CMS2*'))

#bTagPFJetMaker
slimcms2.extend(cms.untracked.vstring('drop *_bTagPFJetMaker_pfjetssoftElectronByIP3dBJetTag_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_bTagPFJetMaker_pfjetssoftElectronByPtBJetTag_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_bTagPFJetMaker_pfjetssoftMuonByIP3dBJetTag_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_bTagPFJetMaker_pfjetssoftMuonByPtBJetTag_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_bTagPFJetMaker_pfjetssoftMuonBJetTag_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_bTagPFJetMaker_pfjetssoftElectronTag_CMS2*'))

#Vertex Collections
slimcms2.extend(cms.untracked.vstring('drop *_davertexMaker_*_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_vertexMakerWithBS_*_CMS2*'))

#GSFTrackMaker
slimcms2.extend(cms.untracked.vstring('drop *_*_gsftrksvertexp4_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_*_gsftrksouterp4_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_*_gsftrksinnerposition_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_*_gsftrksouterposition_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_*_gsftrkslayer1layer_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_*_gsftrkslayer1sizerphi_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_*_gsftrkslayer1sizerz_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_*_gsftrkslayer1charge_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_*_gsftrkslayer1det_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_*_gsftrksd0corrPhi_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_*_gsftrksnlayers3D_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_*_gsftrksnlayersLost_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_*_gsftrkslostpixelhits_CMS2*'))

#Other Track-related Makers
slimcms2.extend(cms.untracked.vstring('drop *_trkToVtxAssMaker_*_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_myTrkJetMetMaker_*_CMS2*'))

#RecoConversionMaker
slimcms2.extend(cms.untracked.vstring('drop *_*_convsrefitPairMomp4_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_*_convsvtxpos_CMS2*'))

#HypMakers
slimcms2.extend(cms.untracked.vstring('drop *_hypDilepVertexMaker_*_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_hypTrilepMaker_*_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_hypQuadlepMaker_*_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_hypDilepMaker_hypotherjetsp4_CMS2*'))

#HypDilepMaker
slimcms2.extend(cms.untracked.vstring('drop *_*_hypnjets_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_*_hypnojets_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_*_hypltvalidHits_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_*_hypltlostHits_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_*_hypltd0_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_*_hypltz0_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_*_hypltd0corr_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_*_hypltz0corr_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_*_hypltchi2_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_*_hypltndof_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_*_hypltd0Err_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_*_hypltz0Err_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_*_hypltptErr_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_*_hypltetaErr_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_*_hypltphiErr_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_*_hyplttrkp4_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_*_hypllvalidHits_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_*_hyplllostHits_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_*_hyplld0_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_*_hypllz0_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_*_hyplld0corr_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_*_hypllz0corr_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_*_hypllchi2_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_*_hypllndof_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_*_hyplld0Err_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_*_hypllz0Err_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_*_hypllptErr_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_*_hyplletaErr_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_*_hypllphiErr_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_*_hyplltrkp4_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_*_hypltdPhiunCorrMet_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_*_hyplldPhiunCorrMet_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_*_hypltdPhimuCorrMet_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_*_hyplldPhimuCorrMet_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_*_hypltdPhitcMet_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_*_hyplldPhitcMet_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_*_hypltdPhimetMuonJESCorr_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_*_hyplldPhimetMuonJESCorr_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_*_hypdPhinJetunCorrMet_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_*_hypdPhinJetmuCorrMet_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_*_hypdPhinJettcMet_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_*_hypdPhinJetmetMuonJESCorr_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_*_hypmt2tcMet_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_*_hypmt2muCorrMet_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_*_hypmt2metMuonJESCorr_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_*_hypjetsidx_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_*_hypotherjetsidx_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_*_hypjetsp4_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_*_hypotherjetsp4_CMS2*'))

#Other Stuff
slimcms2.extend(cms.untracked.vstring('drop *_electronMaker_elsconvsposp4_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_pfElectronMaker_pfelsposAtEcalp4_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_puSummaryInfoMaker_puInfosumpthighpt_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_puSummaryInfoMaker_puInfozpositions_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_puSummaryInfoMaker_puInfosumptlowpt_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_puSummaryInfoMaker_puInfontrkshighpt_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_puSummaryInfoMaker_puInfontrkslowpt_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_jetToElAssMaker_jetsclosestElectronDR_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_jetToMuAssMaker_jetsclosestMuonDR_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_muonMaker_musgfitouterPosp4_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_muonMaker_musfitfirsthitp4_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_muonMaker_musfitdefaultp4_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_muonMaker_musfitpickyp4_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_muonMaker_musecalposp4_CMS2*'))
slimcms2.extend(cms.untracked.vstring('drop *_scMaker_scsvtxp4_CMS2*'))
