import FWCore.ParameterSet.Config as cms

process = cms.Process("Filter")
process.load("CMS2.NtupleMaker.theFilter_cfi")

process.maxEvents = cms.untracked.PSet(
    input = cms.untracked.int32(-1)
)
process.options = cms.untracked.PSet(
    Rethrow = cms.untracked.vstring('ProductNotFound')
)
process.source = cms.Source("PoolSource",
    skipEvents = cms.untracked.uint32(0),
    fileNames = cms.untracked.vstring('file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_101.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_103.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_105.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_106.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_108.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_109.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_10.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_110.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_112.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_113.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_114.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_116.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_117.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_118.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_119.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_11.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_120.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_122.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_123.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_124.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_125.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_126.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_127.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_128.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_129.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_12.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_130.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_131.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_132.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_133.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_134.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_135.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_137.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_138.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_139.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_13.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_140.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_141.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_142.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_143.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_145.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_146.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_147.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_148.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_149.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_14.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_150.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_151.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_15.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_16.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_19.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_1.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_20.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_21.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_22.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_25.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_26.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_27.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_28.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_29.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_2.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_30.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_31.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_32.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_34.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_35.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_36.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_37.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_38.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_39.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_3.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_40.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_41.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_42.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_43.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_44.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_45.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_47.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_48.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_49.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_4.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_50.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_52.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_53.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_56.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_57.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_58.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_59.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_5.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_60.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_61.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_63.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_65.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_6.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_70.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_71.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_72.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_74.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_77.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_80.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_83.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_85.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_86.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_8.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_90.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_91.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_92.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_97.root', 
        'file:/data/tmp/jmuelmen/cms2-pass1/ww/ntuple_signal_9.root')
)

process.outMod = cms.OutputModule("PoolOutputModule",
    outputCommands = cms.untracked.vstring('drop *', 
        'keep *_*_*_B'),
    fileName = cms.untracked.string('/data/tmp/ww_filtered.root')
)

process.outpath = cms.EndPath(process.theFilter*process.outMod)

